export const MOCK_RESIDUAL_VALUES = [
  {
    id: 1,
    source_type: 'lease',
    maker_name: '현대',
    model_name: '아반떼',
    lineup_name: '1.6 가솔린',
    detail_model_name: '인스퍼레이션',
    term_months: 48,
    annual_mileage_km: 20000,
    finance_name: 'KB캐피탈',
    residual_value_percent: 56.2,
    snapshot_month: '2026-03-01',
  },
  {
    id: 2,
    source_type: 'lease',
    maker_name: '현대',
    model_name: '아반떼',
    lineup_name: '1.6 가솔린',
    detail_model_name: '인스퍼레이션',
    term_months: 48,
    annual_mileage_km: 20000,
    finance_name: '신한카드',
    residual_value_percent: 54.7,
    snapshot_month: '2026-03-01',
  },
  {
    id: 3,
    source_type: 'lease',
    maker_name: '기아',
    model_name: '쏘렌토',
    lineup_name: '2.2 디젤',
    detail_model_name: '시그니처',
    term_months: 60,
    annual_mileage_km: 20000,
    finance_name: '우리금융캐피탈',
    residual_value_percent: 58.5,
    snapshot_month: '2026-03-01',
  },
  {
    id: 4,
    source_type: 'lease',
    maker_name: '기아',
    model_name: '쏘렌토',
    lineup_name: '2.2 디젤',
    detail_model_name: '시그니처',
    term_months: 60,
    annual_mileage_km: 20000,
    finance_name: 'BNK캐피탈',
    residual_value_percent: 57.1,
    snapshot_month: '2026-03-01',
  },
  {
    id: 5,
    source_type: 'lease',
    maker_name: 'BMW',
    model_name: '5시리즈',
    lineup_name: '520i',
    detail_model_name: 'M Sport',
    term_months: 36,
    annual_mileage_km: 15000,
    finance_name: '하나캐피탈',
    residual_value_percent: 61.8,
    snapshot_month: '2026-03-01',
  },
  {
    id: 6,
    source_type: 'lease',
    maker_name: 'BMW',
    model_name: '5시리즈',
    lineup_name: '520i',
    detail_model_name: 'M Sport',
    term_months: 36,
    annual_mileage_km: 15000,
    finance_name: 'KB캐피탈',
    residual_value_percent: 60.4,
    snapshot_month: '2026-03-01',
  },
  {
    id: 7,
    source_type: 'rent',
    maker_name: '현대',
    model_name: '쏘나타',
    lineup_name: '2.0 가솔린',
    detail_model_name: '프리미엄',
    term_months: 60,
    annual_mileage_km: 20000,
    finance_name: '오릭스캐피탈',
    residual_value_percent: 49.2,
    snapshot_month: '2026-03-01',
  },
  {
    id: 8,
    source_type: 'rent',
    maker_name: '현대',
    model_name: '쏘나타',
    lineup_name: '2.0 가솔린',
    detail_model_name: '프리미엄',
    term_months: 60,
    annual_mileage_km: 20000,
    finance_name: 'KB캐피탈',
    residual_value_percent: 47.9,
    snapshot_month: '2026-03-01',
  },
  {
    id: 9,
    source_type: 'rent',
    maker_name: '기아',
    model_name: 'K8',
    lineup_name: '2.5 가솔린',
    detail_model_name: '노블레스',
    term_months: 48,
    annual_mileage_km: 20000,
    finance_name: '우리금융캐피탈',
    residual_value_percent: 52.1,
    snapshot_month: '2026-03-01',
  },
  {
    id: 10,
    source_type: 'rent',
    maker_name: '기아',
    model_name: 'K8',
    lineup_name: '2.5 가솔린',
    detail_model_name: '노블레스',
    term_months: 48,
    annual_mileage_km: 20000,
    finance_name: '롯데오토',
    residual_value_percent: 50.6,
    snapshot_month: '2026-03-01',
  },
  {
    id: 11,
    source_type: 'rent',
    maker_name: '제네시스',
    model_name: 'G80',
    lineup_name: '2.5 터보',
    detail_model_name: 'AWD',
    term_months: 48,
    annual_mileage_km: 15000,
    finance_name: '신한카드',
    residual_value_percent: 55.3,
    snapshot_month: '2026-03-01',
  },
  {
    id: 12,
    source_type: 'rent',
    maker_name: '제네시스',
    model_name: 'G80',
    lineup_name: '2.5 터보',
    detail_model_name: 'AWD',
    term_months: 48,
    annual_mileage_km: 15000,
    finance_name: '하나캐피탈',
    residual_value_percent: 54.1,
    snapshot_month: '2026-03-01',
  },
  {
    id: 13,
    source_type: 'lease',
    maker_name: '현대',
    model_name: '아반떼',
    lineup_name: '1.6 가솔린',
    detail_model_name: '인스퍼레이션',
    term_months: 48,
    annual_mileage_km: 20000,
    finance_name: 'KB캐피탈',
    residual_value_percent: 53.2,
    snapshot_month: '2026-02-01',
  },
  {
    id: 14,
    source_type: 'lease',
    maker_name: '기아',
    model_name: '쏘렌토',
    lineup_name: '2.2 디젤',
    detail_model_name: '시그니처',
    term_months: 60,
    annual_mileage_km: 20000,
    finance_name: '우리금융캐피탈',
    residual_value_percent: 59.4,
    snapshot_month: '2026-02-01',
  },
  {
    id: 15,
    source_type: 'lease',
    maker_name: 'BMW',
    model_name: '5시리즈',
    lineup_name: '520i',
    detail_model_name: 'M Sport',
    term_months: 36,
    annual_mileage_km: 15000,
    finance_name: '하나캐피탈',
    residual_value_percent: 60.1,
    snapshot_month: '2026-02-01',
  },
  {
    id: 16,
    source_type: 'rent',
    maker_name: '현대',
    model_name: '쏘나타',
    lineup_name: '2.0 가솔린',
    detail_model_name: '프리미엄',
    term_months: 60,
    annual_mileage_km: 20000,
    finance_name: '오릭스캐피탈',
    residual_value_percent: 50.1,
    snapshot_month: '2026-02-01',
  },
  {
    id: 17,
    source_type: 'rent',
    maker_name: '기아',
    model_name: 'K8',
    lineup_name: '2.5 가솔린',
    detail_model_name: '노블레스',
    term_months: 48,
    annual_mileage_km: 20000,
    finance_name: '우리금융캐피탈',
    residual_value_percent: 53.8,
    snapshot_month: '2026-02-01',
  },
  {
    id: 18,
    source_type: 'rent',
    maker_name: '제네시스',
    model_name: 'G80',
    lineup_name: '2.5 터보',
    detail_model_name: 'AWD',
    term_months: 48,
    annual_mileage_km: 15000,
    finance_name: '신한카드',
    residual_value_percent: 54.0,
    snapshot_month: '2026-02-01',
  },
] as const

export const MOCK_UPLOADS = [
  {
    id: 'mock-upload-202603',
    source_file_name: 'cartner_residual_values_report_202603.xlsx',
    snapshot_month: '2026-03-01',
    total_rows: 21747,
    invalid_rows: 18,
    status: 'completed',
    created_at: '2026-03-07T10:25:00+09:00',
  },
  {
    id: 'mock-upload-202602',
    source_file_name: 'cartner_residual_values_report_202602.xlsx',
    snapshot_month: '2026-02-01',
    total_rows: 21384,
    invalid_rows: 9,
    status: 'completed',
    created_at: '2026-02-07T09:40:00+09:00',
  },
  {
    id: 'mock-upload-202601',
    source_file_name: 'cartner_residual_values_report_202601.xlsx',
    snapshot_month: '2026-01-01',
    total_rows: 20890,
    invalid_rows: 51,
    status: 'failed',
    created_at: '2026-01-08T15:12:00+09:00',
  },
] as const
